# Generated by Django 5.1.1 on 2024-09-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
            ],
        ),
    ]
